### ISSUE TITLE
bzlmod support

### ISSUE THREAD

**Issue by betaboon** [bazel-contrib/rules_debian_packages#20]

**Comment by alexeagle** [comment]
I can help with this one, you can assign me

**Comment by betaboon** [comment]
thanks. that would be awesome :)

**Comment by darkrift** [comment]
Any update on that effort ?

**Comment by blockjon-dd** [comment]
I'm told I should use bzlmod for everything, but we use debian base images. Is there another solution I should look at?

**Comment by alexeagle** [comment]
Oh look I'm assigned here... 🙄 

@thesayyn when will you be ready to merge the rules_distroless effort with this repo?

**Comment by steve-261370** [comment]
I'm going to assume that rules_debian_packages will be deprecated and that rules_distroless is going to be the recommended rule package to use moving forward?

I saw that @thesayyn has implemented apt support in https://github.com/GoogleContainerTools/rules_distroless/pull/16 

I took it for a spin, and migrating to it wasn't too hard.  I followed the example in https://github.com/GoogleContainerTools/rules_distroless/tree/v0.3.2/examples/apt .  Though it's not as smooth as the well-documented rules_debian_packages.

**Comment by betaboon** [comment]
@steve-261370 yep. we recently discussed deprecating this in favor of rules_distroless.
This is happening now: https://github.com/bazel-contrib/rules_debian_packages/issues/53
