### ISSUE TITLE
Drop python dependency

### ISSUE THREAD

**Issue by alexeagle** [bazel-contrib/rules_debian_packages#30]
rules_python is a heavy dependency. It claims to have bzlmod support only in "beta", getting a hermetic interpreter in a repository rule context is a challenge, and installing dependencies from pypi is hard to get right (users have to do all this stuff https://github.com/betaboon/rules_debian_packages/blob/main/WORKSPACE.bazel#L27-L38)

@thesaynn has studied this a bit, and from writing rules_apko has a bunch of experience with handling package manager lockfiles purely in starlark. So we think it may be feasible to port the whole https://github.com/betaboon/rules_debian_packages/tree/main/debian_packages/private/lockfile_generator to starlark and drop the need for third-party packages.

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
