### ISSUE TITLE
Cannot load via Bzlmod

### ISSUE THREAD

**Issue by artysed** [bazel-contrib/rules_debian_packages#36]
Hey! 
I'm trying to add `rules_debian_packages` using Bzlmod how it's written in doc:

```bazel
bazel_dep(
    name = "rules_debian_packages",
    version = "0.2.0",
)
```
but bazel cannot find this dependency in registry:
```
ERROR: in module dependency chain <root> -> rules_debian_packages@0.2.0: module not found in registries: rules_debian_packages@0.2.0
```

What am I doing wrong?

**Comment by betaboon** [comment]
bzlmod is not yet supported.
the tracking issue is here: https://github.com/bazel-contrib/rules_debian_packages/issues/20

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
