### ISSUE TITLE
Debian Packages With Many Transitive Dependencies Cause "max depth exceeded" Error

### ISSUE THREAD

**Issue by wevonosky** [bazel-contrib/rules_debian_packages#42]
In trying to build an image with `rules_oci` that runs a python file, I have found that including `ffmpeg` as a tar layer to `oci_image` causes a `max depth exceeded` error. It seems like the `debian_package_layer` rule recursively generates layers for each dependency causing too many layers. 

My setup is essentially a combination of the [rules_oci python example](https://github.com/bazel-contrib/rules_oci/blob/main/docs/python.md) and the [oci example](https://github.com/bazel-contrib/rules_debian_packages/tree/main/examples/rules_oci) in this repo. My `packages.yaml` file contains a single package (ffmpeg). There are only 3 other tar layers being added, one for the python interpreter, one for dependencies, and one app layer. 

Would love to be proven wrong here, but it seems like there needs to be a way to include a debian package as a single layer.

**Comment by betaboon** [comment]
hello there.

it is possible to merge multiple debian-packages into a single layer with stock `rules_pkg`.

e.g. like this:
```
pkg_tar(
    name = "layer_tesseract_packages",
    deps = [
        debian_package_layer("ffmpeg"),
        debian_package_layer("some-other-package"),
    ],
)
```

This will effectively merge the package and all transitive-dependencies into a single tar.

**Comment by wevonosky** [comment]
Thank you that did the trick!
