### ISSUE TITLE
How to add third party apt repositories?

### ISSUE THREAD

**Issue by juanique** [bazel-contrib/rules_debian_packages#45]
Is it possible to create an image using `rules_debian_packages` and have docker installed in it?

Looking at https://docs.docker.com/engine/install/debian/, these are the steps to get docker installed:

```
# Add Docker's official GPG key:
sudo apt-get update
sudo apt-get install ca-certificates curl
sudo install -m 0755 -d /etc/apt/keyrings
sudo curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
sudo chmod a+r /etc/apt/keyrings/docker.asc

# Add the repository to Apt sources:
echo \
  "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian \
  $(. /etc/os-release && echo "$VERSION_CODENAME") stable" | \
  sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
sudo apt-get update

 sudo apt-get install docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
```

Is there a way to make those packages available as `debian_package_layer` targets?

**Comment by betaboon** [comment]
never tried anything like this and there is currently no explicit support for this in the ruleset.

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
