### ISSUE TITLE
"max depth exceeded" error when building oci_image

### ISSUE THREAD

**Issue by blockjon** [bazel-contrib/rules_debian_packages#47]
```
oci_image(
    name = "cicd-tools",
    base = "//source/proj/docker/python_base:python",
    tars = [
        debian_package_layer("parallel"),
        debian_package_layer("lz4"),
        debian_package_layer("software-properties-common"),
        debian_package_layer("lsb-release"),
        "jq_genrule",
    ],
    visibility = ["//visibility:public"],
)
```
Building this gives me a failure with error message "max depth exceeded"

**Comment by blockjon-dd** [comment]
answering my own question here - looks like i can combine several of them with pkg_tar. based on what im seeing in public open source github repo examples, this is likely the solution to my own question.

**Comment by betaboon** [comment]
heya there.

a similiar question came up before here: https://github.com/bazel-contrib/rules_debian_packages/issues/42

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
