### ISSUE TITLE
New release for Ubuntu support

### ISSUE THREAD

**Issue by nikonikolov** [bazel-contrib/rules_debian_packages#51]
Can you make a new release such that it includes the commit that adds ubuntu support https://github.com/bazel-contrib/rules_debian_packages/commit/9e6c16f5c6e57ac6a8aa3053b4619caa5dcf0c07. Thanks

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
