### ISSUE TITLE
Unpacking Binaries into Runfiles: is it a use-case?

### ISSUE THREAD

**Issue by HunterCrosland** [bazel-contrib/rules_debian_packages#52]
I'd like to be able to unpack a debian's binaries directly into my runfiles so as to utilize them in an app/script. Our images are heavy (which will hopefully be alleviated somewhat by the inclusion of this repo in ours), so installing debs as part of image layers is expensive, and it's much easier to run the app natively.

Is this possible using the repo as-is?

**Comment by betaboon** [comment]
`rules_debian_packages` is being deprecated in favor of `rules_distroless`.
See https://github.com/bazel-contrib/rules_debian_packages/issues/53
